language: ruby
rvm:
  - 2.2.5
  - 2.3.0
  - 2.3.1
gemfile:
  - Gemfile
branches:
  only:
    - master
    - staging
    - /gh(?:\d)+(?:-.+)?/
    - /dev_ver_\d+\.\d+/
before_install: gem update bundler
script: rake ci:travis
