language: ruby
#rvm:
#- 1.9.3
#- 2.0.0
#- 2.2.1
#- 2.2.2
#- 2.2.3
#- 2.2.4
#- 2.2.5
#- 2.2.6
#- 2.2.7
#- 2.2.8
#- 2.2.9
#- 2.3.0
#- 2.3.1
#- 2.3.2
#- 2.3.3
#- 2.3.4
#- 2.3.5
#- 2.3.6
#- jruby-1.7.20.1
#gemfile:
#- gemfiles/rails3
#- gemfiles/rails4
#- gemfiles/rails5
matrix:
  include:
  - rvm: 1.9.3
    gemfile: gemfiles/rails3
  - rvm: 1.9.3
    gemfile: gemfiles/rails4
  - rvm: 2.0.0
    gemfile: gemfiles/rails3
  - rvm: 2.0.0
    gemfile: gemfiles/rails4
  - rvm: 2.2.1
    gemfile: gemfiles/rails3
  - rvm: 2.2.1
    gemfile: gemfiles/rails4
  - rvm: 2.2.2
    gemfile: gemfiles/rails3
  - rvm: 2.2.2
    gemfile: gemfiles/rails4
  - rvm: 2.2.2
    gemfile: gemfiles/rails5
  - rvm: 2.2.3
    gemfile: gemfiles/rails3
  - rvm: 2.2.3
    gemfile: gemfiles/rails4
  - rvm: 2.2.3
    gemfile: gemfiles/rails5
  - rvm: 2.2.4
    gemfile: gemfiles/rails3
  - rvm: 2.2.4
    gemfile: gemfiles/rails4
  - rvm: 2.2.4
    gemfile: gemfiles/rails5
  - rvm: 2.2.5
    gemfile: gemfiles/rails3
  - rvm: 2.2.5
    gemfile: gemfiles/rails4
  - rvm: 2.2.5
    gemfile: gemfiles/rails5
  - rvm: 2.2.6
    gemfile: gemfiles/rails3
  - rvm: 2.2.6
    gemfile: gemfiles/rails4
  - rvm: 2.2.6
    gemfile: gemfiles/rails5
  - rvm: 2.2.7
    gemfile: gemfiles/rails3
  - rvm: 2.2.7
    gemfile: gemfiles/rails4
  - rvm: 2.2.7
    gemfile: gemfiles/rails5
  - rvm: 2.2.8
    gemfile: gemfiles/rails3
    before_install: gem install bundler -v '1.16.6'
  - rvm: 2.2.8
    gemfile: gemfiles/rails4
    before_install: gem install bundler -v '1.16.6'
  - rvm: 2.2.8
    gemfile: gemfiles/rails5
    before_install: gem install bundler -v '1.16.6'
  - rvm: 2.2.9
    gemfile: gemfiles/rails3
    before_install: gem install bundler -v '1.16.6'
  - rvm: 2.2.9
    gemfile: gemfiles/rails4
    before_install: gem install bundler -v '1.16.6'
  - rvm: 2.2.9
    gemfile: gemfiles/rails5
    before_install: gem install bundler -v '1.16.6'
  - rvm: 2.3.0
    gemfile: gemfiles/rails3
  - rvm: 2.3.0
    gemfile: gemfiles/rails4
  - rvm: 2.3.0
    gemfile: gemfiles/rails5
  - rvm: 2.3.1
    gemfile: gemfiles/rails3
  - rvm: 2.3.1
    gemfile: gemfiles/rails4
  - rvm: 2.3.1
    gemfile: gemfiles/rails5
  - rvm: 2.3.2
    gemfile: gemfiles/rails3
  - rvm: 2.3.2
    gemfile: gemfiles/rails4
  - rvm: 2.3.2
    gemfile: gemfiles/rails5
  - rvm: 2.3.3
    gemfile: gemfiles/rails3
  - rvm: 2.3.3
    gemfile: gemfiles/rails4
  - rvm: 2.3.3
    gemfile: gemfiles/rails5
  - rvm: 2.3.4
    gemfile: gemfiles/rails3
  - rvm: 2.3.4
    gemfile: gemfiles/rails4
  - rvm: 2.3.4
    gemfile: gemfiles/rails5
  - rvm: 2.3.5
    gemfile: gemfiles/rails3
  - rvm: 2.3.5
    gemfile: gemfiles/rails4
  - rvm: 2.3.5
    gemfile: gemfiles/rails5
  - rvm: 2.3.6
    gemfile: gemfiles/rails3
  - rvm: 2.3.6
    gemfile: gemfiles/rails4
  - rvm: 2.3.6
    gemfile: gemfiles/rails5
#  - rvm: jruby-1.7.20.1
#    gemfile: gemfiles/rails3
#    before_install: gem install bundler -v '1.16.1'
#  - rvm: jruby-1.7.20.1
#    gemfile: gemfiles/rails4
#    before_install: gem install bundler -v '1.16.1'
#  - rvm: jruby-1.7.20.1
#    gemfile: gemfiles/rails5
#    before_install: gem install bundler -v '1.16.1'
branches:
  only:
  - master
  - staging
  - "/gh(?:\\d)+(?:-.+)?/"
  - "/dev_ver_\\d+\\.\\d+/"
before_install: gem update bundler
script: rake ci:travis
