language: ruby
rvm:
  - 2.2.0
  - 2.2.1
  - 2.2.2
  - 2.2.3
  - 2.2.4
  - 2.2.5
  - 2.2.6
  - 2.2.7
  - 2.2.8
  - 2.2.9
  - 2.3.0
  - 2.3.1
  - 2.3.2
  - 2.3.3
  - 2.3.4
  - 2.3.5
  - 2.3.6
  - 2.4.0
  - 2.4.1
  - 2.4.2
  - 2.4.3
gemfile:
  - Gemfile
branches:
  only:
    - master
    - staging
    - /gh(?:\d)+(?:-.+)?/
    - /dev_ver_\d+\.\d+/
before_install: gem update bundler
script: bundle exec rspec
notifications:
  slack:
    on_success: always
    secure: "F/wN7aMLwR14sLVhz5AZtQNpVQ1hi4ttW5OzvRxS7Oe0pQJtNhyGayx0SCqQ5FbDrwKUsZTHXByLUUG1eUacUwbjtlrr2d0PW1jByLlI7G4alu533mk7uKkBYCWoEa6gwSta1Ac5TYFnz/iHrkIDwh2iIiRZTM+MF9AnNIhwjE8="
