language: ruby
rvm:
  - 2.0.0
  - 2.2.1
  - 2.3.0
  - jruby-1.7.4
  - jruby-9.0.0
gemfile:
  - Gemfile
branches:
  only:
    - master
    - staging
    - /gh(?:\d)+(?:-.+)?/
    - /dev_ver_\d+\.\d+/
before_install: gem update bundler
script: rake ci:travis
