language: ruby
rvm:
  - 1.9.3
  - 2.0.0
gemfile:
  - Gemfile
  - gemfiles/rails3
branches:
  only:
    - master
    - staging
    - /gh(?:\d)+(?:-.+)?/
    - /dev_ver_\d+\.\d+/
script: rake ci:travis
