language: ruby
rvm:
  - 2.3.0
  - 2.3.1
  - 2.3.2
  - 2.3.3
  - 2.3.4
  - 2.3.5
  - 2.3.6
  - 2.4.0
  - 2.4.1
  - 2.4.2
  - 2.4.3
gemfile:
  - Gemfile
branches:
  only:
    - master
    - staging
    - /gh(?:\d)+(?:-.+)?/
    - /dev_ver_\d+\.\d+/
before_install: gem update bundler
script: bundle exec rspec
notifications:
  slack:
    on_success: always
    on_failure: always
    rooms:
    - secure: VxFEOknGE8gcsGk8yE/iogjSogR6fs/IO3keCOHQl/krrGJGy3Lj6lxOdSQ2he+qMaoJs4HgSJRSedpJ3++U26FDtYbhv4S4TUVZ6wo8baVabhU0jCTvG2DNRiDnHTdFWagehanwcFo76hoPxvEAaQcifbVoQQ9/ZYwX9lk9nBo=
