#!/bin/bash

bundle exec rspec spec/osm/api_spec.rb spec/osm/model_spec.rb \
spec/osm/section_spec.rb spec/osm/activity_spec.rb \
spec/osm/api_access_spec.rb spec/osm/badge_spec.rb spec/osm/badges_spec.rb
